// City photographs from Wikimedia Commons, self-hosted in public/photos at two widths
// (each WebP embeds its source and licence).
// Every photo is credited, with its licence, on the About page.
export type Photo = { src: string; src2x: string; title: string; artist: string; license: string; licenseUrl: string; page: string };

export const COMPANY_PHOTOS: Record<string, Photo> = {
  Google: {"src": "/photos/google-500.webp", "title": "Skyline of Varthur, Bangalore", "artist": "SlowPhoton", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Skyline_of_Varthur,_Bangalore.jpg", "src2x": "/photos/google-960.webp"},
  IBM: {"src": "/photos/ibm-500.webp", "title": "Bangalore Skyline from Lal Bagh", "artist": "Innocentbunny", "license": "CC BY-SA 3.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0", "page": "https://commons.wikimedia.org/wiki/File:Bangalore_Skyline_from_Lal_Bagh.jpg", "src2x": "/photos/ibm-960.webp"},
  Swiggy: {"src": "/photos/swiggy-500.webp", "title": "Bangalore skyline (7121517855)", "artist": "Saad Faruque from Bangalore, India", "license": "CC BY-SA 2.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0", "page": "https://commons.wikimedia.org/wiki/File:Bangalore_skyline_(7121517855).jpg", "src2x": "/photos/swiggy-960.webp"},
  Cisco: {"src": "/photos/cisco-500.webp", "title": "Bangalore skyline 2011 (6720868413)", "artist": "Saad Faruque from Bangalore, India", "license": "CC BY 2.0", "licenseUrl": "https://creativecommons.org/licenses/by/2.0", "page": "https://commons.wikimedia.org/wiki/File:Bangalore_skyline_2011_(6720868413).jpg", "src2x": "/photos/cisco-960.webp"},
  Deloitte: {"src": "/photos/deloitte-500.webp", "title": "Mumbai 03-2016 27 skyline at Marine Drive", "artist": "A.Savin", "license": "FAL", "licenseUrl": "http://artlibre.org/licence/lal/en", "page": "https://commons.wikimedia.org/wiki/File:Mumbai_03-2016_27_skyline_at_Marine_Drive.jpg", "src2x": "/photos/deloitte-960.webp"},
  TCS: {"src": "/photos/tcs-500.webp", "title": "Mumbai 03-2016 09 skyline of Lotus Colony", "artist": "A.Savin", "license": "FAL", "licenseUrl": "http://artlibre.org/licence/lal/en", "page": "https://commons.wikimedia.org/wiki/File:Mumbai_03-2016_09_skyline_of_Lotus_Colony.jpg", "src2x": "/photos/tcs-960.webp"},
  Microsoft: {"src": "/photos/microsoft-500.webp", "title": "Financial District, Hyderabad - Skyline featuring Aparna Zenon and SAS iRA under construction", "artist": "iMahesh", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Financial_District,_Hyderabad_-_Skyline_featuring_Aparna_Zenon_and_SAS_iRA_under_construction.jpg", "src2x": "/photos/microsoft-960.webp"},
  Wipro: {"src": "/photos/wipro-500.webp", "title": "Nanakramguda, Hyderabad - Emerging high-rise skyline with construction cranes and IT corridor towers", "artist": "iMahesh", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Nanakramguda,_Hyderabad_-_Emerging_high-rise_skyline_with_construction_cranes_and_IT_corridor_towers.jpg", "src2x": "/photos/wipro-960.webp"},
  Amazon: {"src": "/photos/amazon-500.webp", "title": "Panorama of Hyderabad skyline from Gandipet", "artist": "iMahesh", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Panorama_of_Hyderabad_skyline_from_Gandipet.jpg", "src2x": "/photos/amazon-960.webp"},
  Infosys: {"src": "/photos/infosys-500.webp", "title": "Skyline of Pune city as seen from The Westin Koregaon Park", "artist": "Randy Breese", "license": "CC BY 2.0", "licenseUrl": "https://creativecommons.org/licenses/by/2.0", "page": "https://commons.wikimedia.org/wiki/File:Skyline_of_Pune_city_as_seen_from_The_Westin_Koregaon_Park.jpg", "src2x": "/photos/infosys-960.webp"},
  Paytm: {"src": "/photos/paytm-500.webp", "title": "Noida Sector 78-76 Skyline night view", "artist": "Divyendu Raj Sharma", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Noida_Sector_78-76_Skyline_night_view.jpg", "src2x": "/photos/paytm-960.webp"},
};

export const HERO_PHOTO: Photo = {"src": "/photos/hero-960.webp", "title": "Financial District, Hyderabad - Wide panoramic skyline view from Nanakramguda to Gachibowli", "artist": "iMahesh", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Financial_District,_Hyderabad_-_Wide_panoramic_skyline_view_from_Nanakramguda_to_Gachibowli.jpg", "src2x": "/photos/hero-1280.webp"};
