// City photographs from Wikimedia Commons, hotlinked at standard thumbnail widths.
// Every photo is credited, with its licence, on the About page.
export type Photo = { src: string; title: string; artist: string; license: string; licenseUrl: string; page: string };

export const COMPANY_PHOTOS: Record<string, Photo> = {
  Google: {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9a/Skyline_of_Varthur%2C_Bangalore.jpg/500px-Skyline_of_Varthur%2C_Bangalore.jpg", "title": "Skyline of Varthur, Bangalore", "artist": "SlowPhoton", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Skyline_of_Varthur,_Bangalore.jpg"},
  IBM: {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/Bangalore_Skyline_from_Lal_Bagh.jpg/500px-Bangalore_Skyline_from_Lal_Bagh.jpg", "title": "Bangalore Skyline from Lal Bagh", "artist": "Innocentbunny", "license": "CC BY-SA 3.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0", "page": "https://commons.wikimedia.org/wiki/File:Bangalore_Skyline_from_Lal_Bagh.jpg"},
  Swiggy: {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c1/Bangalore_skyline_%287121517855%29.jpg/500px-Bangalore_skyline_%287121517855%29.jpg", "title": "Bangalore skyline (7121517855)", "artist": "Saad Faruque from Bangalore, India", "license": "CC BY-SA 2.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0", "page": "https://commons.wikimedia.org/wiki/File:Bangalore_skyline_(7121517855).jpg"},
  Cisco: {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Bangalore_skyline_2011_%286720868413%29.jpg/500px-Bangalore_skyline_2011_%286720868413%29.jpg", "title": "Bangalore skyline 2011 (6720868413)", "artist": "Saad Faruque from Bangalore, India", "license": "CC BY 2.0", "licenseUrl": "https://creativecommons.org/licenses/by/2.0", "page": "https://commons.wikimedia.org/wiki/File:Bangalore_skyline_2011_(6720868413).jpg"},
  Deloitte: {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/74/Mumbai_03-2016_27_skyline_at_Marine_Drive.jpg/500px-Mumbai_03-2016_27_skyline_at_Marine_Drive.jpg", "title": "Mumbai 03-2016 27 skyline at Marine Drive", "artist": "A.Savin", "license": "FAL", "licenseUrl": "http://artlibre.org/licence/lal/en", "page": "https://commons.wikimedia.org/wiki/File:Mumbai_03-2016_27_skyline_at_Marine_Drive.jpg"},
  TCS: {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/Mumbai_03-2016_09_skyline_of_Lotus_Colony.jpg/500px-Mumbai_03-2016_09_skyline_of_Lotus_Colony.jpg", "title": "Mumbai 03-2016 09 skyline of Lotus Colony", "artist": "A.Savin", "license": "FAL", "licenseUrl": "http://artlibre.org/licence/lal/en", "page": "https://commons.wikimedia.org/wiki/File:Mumbai_03-2016_09_skyline_of_Lotus_Colony.jpg"},
  Microsoft: {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Financial_District%2C_Hyderabad_-_Skyline_featuring_Aparna_Zenon_and_SAS_iRA_under_construction.jpg/500px-Financial_District%2C_Hyderabad_-_Skyline_featuring_Aparna_Zenon_and_SAS_iRA_under_construction.jpg", "title": "Financial District, Hyderabad - Skyline featuring Aparna Zenon and SAS iRA under construction", "artist": "iMahesh", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Financial_District,_Hyderabad_-_Skyline_featuring_Aparna_Zenon_and_SAS_iRA_under_construction.jpg"},
  Wipro: {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Nanakramguda%2C_Hyderabad_-_Emerging_high-rise_skyline_with_construction_cranes_and_IT_corridor_towers.jpg/500px-Nanakramguda%2C_Hyderabad_-_Emerging_high-rise_skyline_with_construction_cranes_and_IT_corridor_towers.jpg", "title": "Nanakramguda, Hyderabad - Emerging high-rise skyline with construction cranes and IT corridor towers", "artist": "iMahesh", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Nanakramguda,_Hyderabad_-_Emerging_high-rise_skyline_with_construction_cranes_and_IT_corridor_towers.jpg"},
  Amazon: {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/Panorama_of_Hyderabad_skyline_from_Gandipet.jpg/500px-Panorama_of_Hyderabad_skyline_from_Gandipet.jpg", "title": "Panorama of Hyderabad skyline from Gandipet", "artist": "iMahesh", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Panorama_of_Hyderabad_skyline_from_Gandipet.jpg"},
  Infosys: {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/Skyline_of_Pune_city_as_seen_from_The_Westin_Koregaon_Park.jpg/500px-Skyline_of_Pune_city_as_seen_from_The_Westin_Koregaon_Park.jpg", "title": "Skyline of Pune city as seen from The Westin Koregaon Park", "artist": "Randy Breese", "license": "CC BY 2.0", "licenseUrl": "https://creativecommons.org/licenses/by/2.0", "page": "https://commons.wikimedia.org/wiki/File:Skyline_of_Pune_city_as_seen_from_The_Westin_Koregaon_Park.jpg"},
  Paytm: {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/Noida_Sector_78-76_Skyline_night_view.jpg/500px-Noida_Sector_78-76_Skyline_night_view.jpg", "title": "Noida Sector 78-76 Skyline night view", "artist": "Divyendu Raj Sharma", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Noida_Sector_78-76_Skyline_night_view.jpg"},
};

export const HERO_PHOTO: Photo = {"src": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/Financial_District%2C_Hyderabad_-_Wide_panoramic_skyline_view_from_Nanakramguda_to_Gachibowli.jpg/1280px-Financial_District%2C_Hyderabad_-_Wide_panoramic_skyline_view_from_Nanakramguda_to_Gachibowli.jpg", "title": "Financial District, Hyderabad - Wide panoramic skyline view from Nanakramguda to Gachibowli", "artist": "iMahesh", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0", "page": "https://commons.wikimedia.org/wiki/File:Financial_District,_Hyderabad_-_Wide_panoramic_skyline_view_from_Nanakramguda_to_Gachibowli.jpg"};
